export const data = [
  {
    id: "1",
    name: "Aaron Miles",
    email: "aaron@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567891,
    gen: "M",
  },
  {
    id: "2",
    name: "Aishwarya Naik",
    email: "aishwarya@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567892,
    gen: "F",
  },

  {
    id: "42",
    name: "Alyona Gov",
    email: "alyonagov@mailinator.com",
    contact_type: "personal",
    phone_num: 1234569999,
    gen: "F",
  },
  {
    id: "43",
    name: "Robin Singh",
    email: "robin@mailinator.com",
    contact_type: "personal",
    phone_num: 1234579999,
    gen: "M",
  },
  {
    id: "44",
    name: "Vijay Vasudevan",
    email: "vijayv@mailinator.com",
    contact_type: "personal",
    phone_num: 1234589999,
    gen: "M",
  },
  {
    id: "45",
    name: "Steve Smith",
    email: "steve@mailinator.com",
    contact_type: "personal",
    phone_num: 1234599999,
    gen: "M",
  },
  {
    id: "46",
    name: "Anirudh Banerjee",
    email: "anirudhb@mailinator.com",
    contact_type: "personal",
    phone_num: 1234199999,
    gen: "M",
  },
];
