export const data = [
  {
    id: "1",
    name: "Aaron Miles",
    email: "aaron@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567891,
    gen: "M",
  },
  {
    id: "2",
    name: "Aishwarya Naik",
    email: "aishwarya@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567892,
    gen: "F",
  },
  {
    id: "3",
    name: "Arvind Kumar",
    email: "arvind@mailinator.com",
    contact_type: "business",
    phone_num: 1234567893,
    gen: "M",
  },
  {
    id: "4",
    name: "Caterina Binotto",
    email: "caterina@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567894,
    gen: "F",
  },
  {
    id: "5",
    name: "Chetan Kumar",
    email: "chetan@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567895,
    gen: "M",
  },
  {
    id: "6",
    name: "Jim McClain",
    email: "jim@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567896,
    gen: "M",
  },
  {
    id: "7",
    name: "Mahaveer Singh",
    email: "mahaveer@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567897,
    gen: "M",
  },
  {
    id: "8",
    name: "Rahul Jain",
    email: "rahul@mailinator.com",
    contact_type: "business",
    phone_num: 1234567898,
    gen: "M",
  },
  {
    id: "9",
    name: "Rizan Khan",
    email: "rizan@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567899,
    gen: "M",
  },
  {
    id: "10",
    name: "Sarah Potter",
    email: "sarah@mailinator.com",
    contact_type: "business",
    phone_num: 1234567819,
    gen: "F",
  },
  {
    id: "11",
    name: "Keshav Muddaiah",
    email: "keshav@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567829,
    gen: "M",
  },
  {
    id: "12",
    name: "Nita Ramesh",
    email: "nita@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567839,
    gen: "F",
  },
  {
    id: "13",
    name: "Julia Hunstman",
    email: "julia@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567849,
    gen: "F",
  },
  {
    id: "14",
    name: "Juan Alonso",
    email: "juan@mailinator.com",
    contact_type: "business",
    phone_num: 1234567859,
    gen: "M",
  },
  {
    id: "15",
    name: "Gabriel Montoya",
    email: "gabriel@mailinator.com",
    contact_type: "business",
    phone_num: 1234567869,
    gen: "F",
  },
  {
    id: "16",
    name: "Beatrice Iglesias",
    email: "beatrice@mailinator.com",
    contact_type: "business",
    phone_num: 1234567879,
    gen: "F",
  },
  {
    id: "17",
    name: "Sarah Symms",
    email: "sarah.s@mailinator.com",
    contact_type: "business",
    phone_num: 1234567889,
    gen: "F",
  },
  {
    id: "18",
    name: "Patrick Pinheiro",
    email: "patrick@mailinator.com",
    contact_type: "business",
    phone_num: 1234567899,
    gen: "M",
  },
  {
    id: "19",
    name: "Anand Patel",
    email: "anand@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567199,
    gen: "M",
  },
  {
    id: "20",
    name: "Kishore Kalburgi",
    email: "kishore@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567299,
    gen: "M",
  },
  {
    id: "21",
    name: "Rebecca Norris",
    email: "rebecca@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567399,
    gen: "F",
  },
  {
    id: "22",
    name: "Özgür Başak",
    email: "ozgur@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567499,
    gen: "M",
  },
  {
    id: "23",
    name: "Robin Andersen",
    email: "robin@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567599,
    gen: "M",
  },
  {
    id: "24",
    name: "Nandini Kumar",
    email: "nandini@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567699,
    gen: "F",
  },
  {
    id: "25",
    name: "Nikita Smith",
    email: "nikita@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567799,
    gen: "F",
  },
  {
    id: "26",
    name: "Colton Doe",
    email: "colton@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567899,
    gen: "M",
  },
  {
    id: "27",
    name: "Alain Senna",
    email: "alain@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567999,
    gen: "F",
  },
  {
    id: "28",
    name: "Ashwin Jain",
    email: "ashwin@mailinator.com",
    contact_type: "personal",
    phone_num: 1234561999,
    gen: "M",
  },
  {
    id: "29",
    name: "Seema Bhatt",
    email: "seema@mailinator.com",
    contact_type: "personal",
    phone_num: 1234562999,
    gen: "F",
  },
  {
    id: "30",
    name: "Kayla Scarpinski",
    email: "kayla@mailinator.com",
    contact_type: "personal",
    phone_num: 1234563999,
    gen: "F",
  },
  {
    id: "31",
    name: "Ajay Ghosh",
    email: "ajay@mailinator.com",
    contact_type: "personal",
    phone_num: 1234564999,
    gen: "M",
  },
  {
    id: "32",
    name: "Chris Lindberg",
    email: "chris@mailinator.com",
    contact_type: "personal",
    phone_num: 1234565999,
    gen: "M",
  },
  {
    id: "33",
    name: "Christina Mourujärvi",
    email: "christina@mailinator.com",
    contact_type: "personal",
    phone_num: 1234566999,
    gen: "F",
  },
  {
    id: "34",
    name: "Mikhail Bill",
    email: "mikhail@mailinator.com",
    contact_type: "personal",
    phone_num: 1234567999,
    gen: "F",
  },
  {
    id: "35",
    name: "Eino Göregen",
    email: "eino@mailinator.com",
    contact_type: "personal",
    phone_num: 1234568999,
    gen: "M",
  },
  {
    id: "36",
    name: "Zachariah Johansson",
    email: "zacharaiah@mailinator.com",
    contact_type: "personal",
    phone_num: 1234569999,
    gen: "M",
  },
  {
    id: "37",
    name: "Aimaan Mohammed",
    email: "aimaan@mailinator.com",
    contact_type: "business",
    phone_num: 1234519999,
    gen: "M",
  },
  {
    id: "38",
    name: "Aika Tsunoda",
    email: "aika@mailinator.com",
    contact_type: "personal",
    phone_num: 1234529999,
    gen: "F",
  },
  {
    id: "39",
    name: "Kimiko Minamoto",
    email: "kimiko@mailinator.com",
    contact_type: "personal",
    phone_num: 1234539999,
    gen: "M",
  },
  {
    id: "40",
    name: "Alyona Baginskaite",
    email: "alyona@mailinator.com",
    contact_type: "personal",
    phone_num: 1234549999,
    gen: "M",
  },
  {
    id: "41",
    name: "Anirudh Mukherjee",
    email: "anirudh@mailinator.com",
    contact_type: "personal",
    phone_num: 1234559999,
    gen: "M",
  },
  {
    id: "42",
    name: "Alyona Gov",
    email: "alyonagov@mailinator.com",
    contact_type: "personal",
    phone_num: 1234569999,
    gen: "F",
  },
  {
    id: "43",
    name: "Robin Singh",
    email: "robin@mailinator.com",
    contact_type: "personal",
    phone_num: 1234579999,
    gen: "M",
  },
  {
    id: "44",
    name: "Vijay Vasudevan",
    email: "vijayv@mailinator.com",
    contact_type: "personal",
    phone_num: 1234589999,
    gen: "M",
  },
  {
    id: "45",
    name: "Steve Smith",
    email: "steve@mailinator.com",
    contact_type: "personal",
    phone_num: 1234599999,
    gen: "M",
  },
  {
    id: "46",
    name: "Anirudh Banerjee",
    email: "anirudhb@mailinator.com",
    contact_type: "personal",
    phone_num: 1234199999,
    gen: "M",
  },
];
